### ISSUE TITLE
To wj88808886/ARIMA 

### ISSUE THREAD

**Issue by iamsmk** [wj88808886/ARIMA#1]
作者您好，最近我在研究时序预测模型ARIMA，对您提交的代码很感兴趣，也测试了一下您的代码，但发现时序样本数较大时，比如10000个以上的时序样本，程序执行速度会比R和SPSS慢很多，调试发现执行时间最长的是在innovation_kernel这一模块，且有两个地方调用了此模块，分别是更新aicc值的innovation_update模块，以及预测阶段的innovation模块。想请教作者：
1. innovation_kernel这一模块主要是实现什么样的功能，为何需要如此高的计算复杂度？
2. 为何在更新aic值以及预测时需要调用innovation_kernel模块？
3. 能否提供相关的参考资料？

很希望能得到作者的答复，谢谢！

**Comment by wj88808886** [comment]
您好，我实际测试的时候确实没试过10000个这么多的数据样本，不知道您是R里的哪个方法做比较...arima()? 请问测试数据是怎么样的。。

我的实现方式是参考R的几个package的，首先是FitARMA的package里面应用了2007年的论文: A. I. McLeod, Ying Zhang (2007). Faster ARMA maximum likelihood estimation, Computational Statistics & Data Analysis 52(4), URL http://dx.doi.org/10.1016/j.csda.2007.07.020. 有兴趣可以去看看。。然后参考了R的itsmr的package用了innovation algorithm来更新aicc和最后做预测。。

主要来说，innovation kernel应该是用来实现innovation algorithm的所以用来做预测了。具体参考itsmr的package说明，包括它的源代码，还有是这本书 Introduction to Time Series and Forecasting, Second Edition Peter J. Brockwell and Richard A. Davis. Itsmr package主要实现了这本书的理论知识。可以参考这本书的第五章，5.1,5.2和5.5.2里面有说明AICC是怎么回事，基本是用了maximum likelihood estimator根据innovation algorithm算出来的值。。

**Comment by iamsmk** [comment]
您好，我跟R的forecast包里面的auto.arima做了比较，测试数据是从time series data library上面下载的internet traffic data，大约有20000个时序样本 
测试数据链接：
https://datamarket.com/data/set/232g/internet-traffic-data-in-bits-from-an-isp-aggregated-traffic-in-the-united-kingdom-academic-network-backbone-it-was-collected-between-19-november-2004-at-0930-hours-and-27-january-2005-at-1111-hours-data-collected-at-five-minute-intervals#!ds=232g&display=line
我们主要是面对大数据时序预测的场景，因此时序样本数会很大。
十分感谢您提供的参考资料及解答，有问题再向您请教，谢谢。
